import { neon } from '@neondatabase/serverless';
import type { FeedbackAnswer } from '@/lib/server/slack-feedback';

/**
 * Recording a feedback answer in the socialagent store, so it can be read on
 * one page rather than only scrolled past in Slack.
 *
 * Mark's ask, 2026-08-21: "can you add a page for the feedback to live in
 * socialagent". Slack still fires, because an answer is worth most on the day
 * it arrives; the row is what makes a PATTERN visible across several answers,
 * which is the actual point of asking.
 *
 * Same runtime path the shop already uses to reach that store for discount
 * lookups and delivery prices: @neondatabase/serverless over
 * ARTICLES_DATABASE_URL, which is already a read-write credential (see
 * recordRedemption in lib/server/discounts.ts). So this needs no new secret.
 *
 * Never throws. A visitor who answered has done their part, and a failure to
 * persist must not turn into an error on their screen or a lost Slack message.
 */
function databaseUrl(): string | undefined {
  return process.env.ARTICLES_DATABASE_URL ?? process.env.DATABASE_URL;
}

const STEP: Record<FeedbackAnswer['step'], 'Q1' | 'Q2' | 'Q3'> = {
  q1: 'Q1',
  q2: 'Q2',
  q3: 'Q3',
};

const PLACEMENT: Record<string, 'PRODUCT' | 'CHECKOUT' | 'PAGE'> = {
  product: 'PRODUCT',
  checkout: 'CHECKOUT',
  page: 'PAGE',
};

export async function recordFeedback(a: FeedbackAnswer): Promise<void> {
  const url = databaseUrl();
  if (!url) return;
  try {
    const sql = neon(url);
    // cuid()-shaped ids are generated by Prisma in the app; a plain uuid is
    // fine here since nothing joins on the format.
    await sql`
      INSERT INTO "Feedback" ("id", "step", "answer", "path", "placement")
      VALUES (
        gen_random_uuid()::text,
        ${STEP[a.step]}::"FeedbackStep",
        ${a.answer},
        ${a.path ?? null},
        ${a.placement ? PLACEMENT[a.placement] : null}::"FeedbackPlacement"
      )
    `;
  } catch (error) {
    console.error('[feedback] could not record the answer:', error);
  }
}
